# ErrorLibrary for UARD - persistent, fail-safe diagnostic memory
# Reporter core intentionally matches OSblocker 1.0.0. Checker selection is the upgrade.
$ErrorLibraryVersion = '1.1.1'
$ErrorLibraryPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) 'error-library.jsonl'
$ErrorLibraryMaxRecordBytes = 32768
function Get-ErrorFingerprint([string]$Text, [string]$Category = 'UNKNOWN') {
    $n = if ($null -eq $Text) { '' } else { [string]$Text }
    $n = $n -replace '(?i)0x[0-9a-f]+', '0xHEX';$n = $n -replace '(?i)https?://[^\s]+', 'URL';$n = $n -replace '\b\d+\b', 'N';$n = $n -replace '\s+', ' ';$n = $n.Trim().ToLowerInvariant();$payload = $Category.ToUpperInvariant() + '|' + $n;$sha = [Security.Cryptography.SHA256]::Create();try { return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($payload)))).Replace('-', '').ToLowerInvariant() }finally { $sha.Dispose() }
}
function Classify-ErrorText([string]$Text) {
    $t = if ($null -eq $Text) { '' } else { [string]$Text }
    if ($t -match '(?i)parse|parser|syntax|unexpected token|missing.*[\)\]\}]|term.*not recognized') { return 'PARSER' };if ($t -match '(?i)access denied|unauthorized|forbidden|permission') { return 'ACCESS' };if ($t -match '(?i)timeout|timed out') { return 'TIMEOUT' };if ($t -match '(?i)not found|cannot find|404') { return 'NOT_FOUND' };if ($t -match '(?i)422|unprocessable') { return 'HTTP_422' };if ($t -match '(?i)409|conflict') { return 'HTTP_409' };if ($t -match '(?i)408|425|429|5\d\d|transient|retry') { return 'NETWORK_TRANSIENT' };if ($t -match '(?i)redirect|301|302|307|308') { return 'REDIRECT' };if ($t -match '(?i)exception|error|failed|failure') { return 'ERROR' };if ($t -match '(?i)warning|warn') { return 'WARNING' };return 'UNKNOWN'
}
function Save-ErrorEvent {
    param([string]$Source, [string]$Stream, [string]$Text, [int]$ExitCode = 0,[int]$HttpStatus = 0, [string]$Artifact = '', [string]$CandidateHash = '',[string]$PreviousCandidateHash = '', [int]$Attempt = 0, [string]$RepairAction = '',[string]$SyntaxResult = '', [string]$Context = '')
    try {$category=Classify-ErrorText $Text;$fingerprint=Get-ErrorFingerprint $Text $category;$record=[ordered]@{schema=1;library_version=$ErrorLibraryVersion;timestamp_utc=[DateTime]::UtcNow.ToString('o');source=$Source;stream=$Stream;artifact=$Artifact;category=$category;fingerprint=$fingerprint;text=([string]$Text).Substring(0,[Math]::Min(([string]$Text).Length,12000));exit_code=$ExitCode;http_status=$HttpStatus;candidate_hash=$CandidateHash;previous_candidate_hash=$PreviousCandidateHash;attempt=$Attempt;repair_action=$RepairAction;syntax_result=$SyntaxResult;context=([string]$Context).Substring(0,[Math]::Min(([string]$Context).Length,12000))};$line=$record|ConvertTo-Json -Compress -Depth 8;if([Text.Encoding]::UTF8.GetByteCount($line)-le$ErrorLibraryMaxRecordBytes){Add-Content -LiteralPath $ErrorLibraryPath -Value $line -Encoding UTF8};return $fingerprint}catch{return $null}
}
function Get-ErrorCount([string]$Fingerprint) {if(-not(Test-Path -LiteralPath $ErrorLibraryPath)){return 0};try{return @(Get-Content -LiteralPath $ErrorLibraryPath -ErrorAction Stop|ForEach-Object{try{$_|ConvertFrom-Json}catch{$null}}|Where-Object{$_ -and $_.fingerprint -eq $Fingerprint}).Count}catch{return 0}}
function Test-DiagnosticNarrative([string]$Text) {
    $t=[string]$Text
    if([string]::IsNullOrWhiteSpace($t)){return $true}
    $known=@('PASS — parser/repair gate complete','[REGRESSION PASS] historical parser failure was reproduced','This test verifies that the script fails safely when given malformed input.','WARNING: expected test narrative, not an emitted warning','Error handling regression coverage complete','The previous failure is intentionally reproduced here.','HTTP 422 deterministic rejection is a regression fixture.','No errors were found.','No error occurred; the regression test passed.','The test failed previously and is now fixed.')
    if($known -contains $t){return $true}
    $pattern='(?i)^(?:\s*(?:pass|passed|success|successful|ok)\b|\[\s*(?:regression\s+)?pass\s*\]|\s*no\s+errors?\s+(?:were\s+)?found\b|\s*no\s+error\s+occurred\b|\s*this\s+test\s+(?:verifies|checks|ensures)\b|\s*the\s+previous\s+(?:failure|error)\s+(?:is|was)\s+(?:intentionally|deliberately)\b|\s*the\s+(?:test|operation|step|command)\s+(?:failed|completed)\s+(?:previously|successfully)\b|\s*error\s+handling\s+.*\bcomplete\b|\s*http\s+\d+\s+.*(?:fixture|regression)\b|\s*warning\s*:.*(?:test|expected|narrative)\b)'
    return [bool]($t -match $pattern)
}
function Get-DiagnosticDecision {
    param([string[]]$Lines,[int]$ExitCode=0,[int]$HttpStatus=0)
    $all=@($Lines|ForEach-Object{[string]$_});$nonEmpty=@($all|Where-Object{-not[string]::IsNullOrWhiteSpace($_)});$explicitPattern='(?i)^\s*\[(?:ERROR|FATAL)\]\s*[:\-]?';$strongPattern='(?i)(ParserError|At line\s+\d+\s+char\s+\d+|At C:\\.*\.ps1:\d+ char:\d+|CommandNotFoundException|UnauthorizedAccessException|Exception calling|FullyQualifiedErrorId\s*:|CategoryInfo\s*:|redirect rejected|Access is denied|The term .* is not recognized|operation timed out|request timed out|timeout occurred|HTTP\s+(?:408|409|422|425|429)|\b5\d\d\b|^\s*(?:\[[^\]]+\]\s*)?(?:ERROR|FATAL)\s*[:\-])';$genericPattern='(?i)(?:^|\s)(error|exception|failed|failure|denied|timeout|timed out|cannot find|not found|unprocessable|conflict|redirect rejected)(?:\b|:)';$batchHasConcrete=($nonEmpty|Where-Object{$_ -match $explicitPattern -or $_ -match $strongPattern}).Count -gt 0;$result=@();foreach($text in $nonEmpty){$narrative=Test-DiagnosticNarrative $text;$explicit=[bool]($text -match $explicitPattern);$strong=[bool]($text -match $strongPattern);$generic=[bool]($text -match $genericPattern);$objective=($ExitCode -ne 0 -or $HttpStatus -ge 400);$emit=($explicit -or $strong -or ($generic -and -not$narrative) -or ($objective -and -not$narrative));$result+=[pscustomobject]@{Text=$text;Emit=$emit;Explicit=$explicit;Strong=$strong;Generic=$generic;Narrative=$narrative;Objective=$objective;BatchHasConcrete=$batchHasConcrete}};return @($result)
}
function Force-DiagnosticScan {
    param([string]$Source='UNKNOWN',[string]$Artifact='',[string[]]$Lines,[int]$ExitCode=0,[int]$HttpStatus=0,[string]$Stage='', [string]$Context='')
    $decisions=@(Get-DiagnosticDecision -Lines $Lines -ExitCode $ExitCode -HttpStatus $HttpStatus);$seen=@{};foreach($d in $decisions){if(-not$d.Emit){continue};$text=[string]$d.Text;$category=Classify-ErrorText $text;$fp=Get-ErrorFingerprint $text $category;if($seen.ContainsKey($fp)){continue};$seen[$fp]=$true;[void](Save-ErrorEvent -Source $Source -Stream 'output-scan' -Text $text -Artifact $Artifact -ExitCode $ExitCode -HttpStatus $HttpStatus -Context ("stage=$Stage; output matched error detector"))};return @($seen.Keys|ForEach-Object{[pscustomobject]@{fingerprint=$_}})
}
function Test-ErrorLike([string]$Text,[int]$ExitCode=0,[int]$HttpStatus=0){if($ExitCode -ne 0 -or $HttpStatus -ge 400){return [bool](-not(Test-DiagnosticNarrative $Text))};$t=[string]$Text;$explicitPattern='(?i)^\s*\[(?:ERROR|FATAL)\]\s*[:\-]?';$pattern='(?i)(ParserError|At line\s+\d+\s+char\s+\d+|At C:\\.*\.ps1:\d+ char:\d+|CommandNotFoundException|UnauthorizedAccessException|Exception calling|FullyQualifiedErrorId\s*:|CategoryInfo\s*:|^\s*(?:\[[^\]]+\]\s*)?(?:ERROR|FATAL)\s*[:\-]|redirect rejected|Access is denied|The term .* is not recognized|operation timed out|request timed out|timeout occurred|timed out)';return [bool]($t -match $explicitPattern -or $t -match $pattern)}
function Scan-ErrorOutput {param([string]$Source='UNKNOWN',[string]$Artifact='',[string[]]$Lines,[int]$ExitCode=0,[int]$HttpStatus=0,[string]$Stage='');return @(Force-DiagnosticScan -Source $Source -Artifact $Artifact -Lines $Lines -ExitCode $ExitCode -HttpStatus $HttpStatus -Stage $Stage)}
function Scan-ErrorLike {param([string]$Source,[string]$Artifact,[string[]]$Lines,[int]$ExitCode=0,[int]$HttpStatus=0,[string]$Stage='');return @(Force-DiagnosticScan @PSBoundParameters)}
function Get-ErrorLibraryRecords {if(-not(Test-Path -LiteralPath $ErrorLibraryPath)){return @()};@(Get-Content -LiteralPath $ErrorLibraryPath|ForEach-Object{try{$_|ConvertFrom-Json}catch{}})}
