param(
    [string]$BaselineSha = '765178ee7c83449064169bb72d4cb1a1cb230b11',
    [int]$Cases = 1000,
    [int]$NetworkTimeoutMilliseconds = 750
)
$ErrorActionPreference='Stop'
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot=Split-Path -Parent $Root
$ReportPath=Join-Path $Root 'osblocker-1.0.0-compatibility-1000-report.json'
$TempRoot=Join-Path $env:TEMP ('osblocker-compat-1000-'+[guid]::NewGuid().ToString('N'))
$TestConfig=Join-Path $TempRoot 'candidate-config.json'
$baselineProcess=$null;$candidateProcess=$null
$report=[ordered]@{status='NOT_CERTIFIED';started_utc=[DateTime]::UtcNow.ToString('o');requested_cases=$Cases;executed_cases=0;baseline_sha=$BaselineSha;categories=[ordered]@{};failures=@();evidence=[ordered]@{}}
function Record([string]$cat,[bool]$ok,[string]$detail){if(-not $report.categories.Contains($cat)){$report.categories[$cat]=[ordered]@{pass=0;fail=0}};if($ok){$report.categories[$cat].pass++}else{$report.categories[$cat].fail++;$report.failures += [ordered]@{category=$cat;case=$report.executed_cases+1;detail=$detail}};$report.executed_cases++;if(($report.executed_cases % 100)-eq 0){Write-Host "COMPAT 1000 PROGRESS $($report.executed_cases)/$Cases"};if(-not $ok){throw "Compatibility case $($report.executed_cases) failed [$cat]: $detail"}}
function StopProc([ref]$p){if($null -ne $p.Value){try{if(-not $p.Value.HasExited){Stop-Process -Id $p.Value.Id -Force -ErrorAction SilentlyContinue}}catch{};$p.Value=$null}}
function Curl([string]$url,[string]$resolve=''){$err=Join-Path $env:TEMP ('compat1000-'+[guid]::NewGuid().ToString('N')+'.err');try{$a=@('--noproxy','*','--ipv4','--connect-timeout','0.5','--max-time',[string]([math]::Max(0.75,$NetworkTimeoutMilliseconds/1000.0)),'--silent','--show-error','--output','NUL');if($resolve){$a+=@('--resolve',$resolve)};$a+=$url;& curl.exe @a --stderr $err;$code=$LASTEXITCODE;$txt='';if(Test-Path $err){$raw=Get-Content $err -Raw -ErrorAction SilentlyContinue;if($null -ne $raw){$txt=$raw.Trim()}};return [pscustomobject]@{ExitCode=$code;Stderr=$txt}}finally{Remove-Item $err -Force -ErrorAction SilentlyContinue}}
function YoutubeIp{$x=@(Resolve-DnsName youtube.com -Type A -DnsOnly -ErrorAction Stop|Where-Object IPAddress|Select-Object -ExpandProperty IPAddress -Unique);if($x.Count -lt 1){throw 'youtube.com returned no IPv4 address.'};return [string]$x[0]}
function StartFilter([string]$filter,[string]$config=$null){$args=@('-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-File',$filter);if($config){$args+=@('-ConfigOverride',$config,'-RefreshSeconds','1')};return Start-Process powershell.exe -ArgumentList $args -PassThru -WindowStyle Hidden}
try{
 if(-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Administrator privileges required.'}
 if(-not (Test-Path (Join-Path $RepoRoot '.git'))){throw 'Git repository required.'}
 New-Item -ItemType Directory -Path $TempRoot -Force|Out-Null
 $archive=Join-Path $TempRoot 'baseline.tar';& git -C $RepoRoot archive --format=tar --output=$archive $BaselineSha 'ultra-mode';if($LASTEXITCODE -ne 0){throw "Baseline archive failed: $LASTEXITCODE"};& tar.exe -xf $archive -C $TempRoot;if($LASTEXITCODE -ne 0){throw "Baseline extraction failed: $LASTEXITCODE"}
 $baselineRoot=Join-Path $TempRoot 'ultra-mode';$baselineFilter=Join-Path $baselineRoot 'packet-filter.ps1';$candidateFilter=Join-Path $Root 'packet-filter.ps1';$baselineConfigPath=Join-Path $baselineRoot 'config.json';$candidateConfigPath=Join-Path $Root 'config.json'
 foreach($p in @($baselineFilter,$candidateFilter,$baselineConfigPath,$candidateConfigPath)){if(-not(Test-Path $p)){throw "Required compatibility artifact missing: $p"}}
 $prodHash=(Get-FileHash $candidateConfigPath -Algorithm SHA256).Hash;$bCfg=Get-Content $baselineConfigPath -Raw|ConvertFrom-Json;$cCfg=Get-Content $candidateConfigPath -Raw|ConvertFrom-Json
 foreach($n in @('enabled','start','end','domains','alwaysBlockedDomains','alwaysAllowedDomains')){Record 'config-contract' ($null -ne $bCfg.$n -and $null -ne $cCfg.$n) "Missing shared config field $n"}
 $test=$cCfg|ConvertTo-Json -Depth 30|ConvertFrom-Json;$test.enabled=$true;$test.start='00:00';$test.end='00:00';$test|ConvertTo-Json -Depth 30|Set-Content $TestConfig -Encoding UTF8
 . (Join-Path $Root 'YouTubePolicy.ps1')
 $ids=@('AAAAAAAAAAA','dQw4w9WgXcQ','BaW_jenozKc','abcdefghijk','01234567890')
 $urlCases=@();foreach($id in $ids){$urlCases += "https://www.youtube.com/watch?v=$id";$urlCases += "https://www.youtube.com/watch?V=$id";$urlCases += "https://www.youtube.com/watch?v=$id&x=1";$urlCases += "https://www.youtube.com/shorts/$id";$urlCases += "https://youtube.com/embed/$id";$urlCases += "https://m.youtube.com/watch?v=$id";$urlCases += "https://www.youtube.com/watch?v=$id%20";$urlCases += "https://www.youtube.com/watch?v=$id#fragment"}
 $cfg=[pscustomobject]@{youtubePolicy=[pscustomobject]@{allowAdditionalQueryParameters=$true};allowedYouTubeVideoIds=@('AAAAAAAAAAA','dQw4w9WgXcQ','BaW_jenozKc')}
 for($i=0;$i -lt 300;$i++){ $u=$urlCases[$i % $urlCases.Count];$r=Resolve-YouTubePolicy $u $cfg;$expected=if($u -match 'watch\?v=(AAAAAAAAAAA|dQw4w9WgXcQ|BaW_jenozKc)($|&)'){ 'ALLOW' } else { 'BLOCK' };Record 'policy-parser-300' ($null -ne $r -and $r.decision -ceq $expected) "$u expected=$expected actual=$($r.decision)" }
 for($i=0;$i -lt 150;$i++){ $x=[pscustomobject]@{youtubePolicy=[pscustomobject]@{allowAdditionalQueryParameters=($i%2 -eq 0)};allowedYouTubeVideoIds=@('AAAAAAAAAAA')};$canonical=Resolve-YouTubePolicy 'https://www.youtube.com/watch?v=AAAAAAAAAAA' $x;$upper=Resolve-YouTubePolicy 'https://www.youtube.com/watch?V=AAAAAAAAAAA' $x;$extra=Resolve-YouTubePolicy ('https://www.youtube.com/watch?v=AAAAAAAAAAA&x='+$i) $x;Record 'policy-config-mutation-150' ($canonical.decision -ceq 'ALLOW' -and $upper.decision -ceq 'BLOCK' -and (($i%2 -eq 0 -and $extra.decision -ceq 'ALLOW') -or ($i%2 -eq 1 -and $extra.decision -ceq 'BLOCK'))) "policy mutation i=$i canonical=$($canonical.decision) upper=$($upper.decision) extra=$($extra.decision)" }
 $baselineExpected=$bCfg.domains;for($i=0;$i -lt 100;$i++){ $copy=$bCfg|ConvertTo-Json -Depth 30|ConvertFrom-Json;$copy.enabled=$true;$copy.start='00:00';$copy.end='00:00';$copy.domains=@($baselineExpected);$copy|ConvertTo-Json -Depth 30|Set-Content $TestConfig -Encoding UTF8;$round=Get-Content $TestConfig -Raw|ConvertFrom-Json;Record 'config-roundtrip-100' ($round.domains.Count -eq @($baselineExpected).Count -and $round.enabled -eq $true) "roundtrip $i changed baseline-shaped config" }
 $candidateConfigHash=$prodHash
 for($i=0;$i -lt 100;$i++){ $candidateProcess=StartFilter $candidateFilter $TestConfig;Start-Sleep -Milliseconds 180;$alive=($null -ne $candidateProcess -and -not $candidateProcess.HasExited);Record 'candidate-lifecycle-100' $alive "1.0.1 exited on lifecycle cycle $i";StopProc ([ref]$candidateProcess);Start-Sleep -Milliseconds 80 }
 $ip=YoutubeIp
 for($i=0;$i -lt 100;$i++){ $candidateProcess=StartFilter $candidateFilter $TestConfig;Start-Sleep -Milliseconds 350;$alive=($null -ne $candidateProcess -and -not $candidateProcess.HasExited);if(-not $alive){Record 'real-network-100' $false "1.0.1 exited before network probe $i";continue};$allow=Curl 'https://pypi.org/';$block=Curl 'https://youtube.com/' "youtube.com:443:$ip";$ok=($allow.ExitCode -eq 0 -and $block.ExitCode -eq 28);Record 'real-network-100' $ok "cycle=$i allow=$($allow.ExitCode) block=$($block.ExitCode)";StopProc ([ref]$candidateProcess);Start-Sleep -Milliseconds 80 }
 $baselineProcess=StartFilter $baselineFilter;Start-Sleep -Seconds 2;Record 'baseline-start-1' ($null -ne $baselineProcess -and -not $baselineProcess.HasExited) '1.0.0 failed to remain alive';$baselineAllow=Curl 'https://pypi.org/';$baselineBlock=Curl 'https://youtube.com/' "youtube.com:443:$ip";Record 'baseline-real-network-2' ($baselineAllow.ExitCode -eq 0 -and $baselineBlock.ExitCode -eq 28) "baseline allow=$($baselineAllow.ExitCode) block=$($baselineBlock.ExitCode)";StopProc ([ref]$baselineProcess)
 $candidateProcess=StartFilter $candidateFilter $TestConfig;Start-Sleep -Seconds 2;Record 'candidate-transition-1' ($null -ne $candidateProcess -and -not $candidateProcess.HasExited) '1.0.1 failed after 1.0.0 teardown';StopProc ([ref]$candidateProcess)
 for($i=0;$i -lt 100;$i++){ $hash=(Get-FileHash $candidateConfigPath -Algorithm SHA256).Hash;Record 'production-integrity-100' ($hash -ceq $candidateConfigHash) "production config hash changed on check $i" }
 for($i=0;$i -lt 142;$i++){ $bc=Get-Content $baselineConfigPath -Raw|ConvertFrom-Json;$cc=Get-Content $candidateConfigPath -Raw|ConvertFrom-Json;$same=$true;foreach($n in @('enabled','start','end','domains','alwaysBlockedDomains','alwaysAllowedDomains')){if($null -eq $bc.$n -or $null -eq $cc.$n){$same=$false}};$policy=Resolve-YouTubePolicy 'https://www.youtube.com/watch?V=AAAAAAAAAAA' $cfg;$same=$same -and ($policy.decision -ceq 'BLOCK');Record 'cross-version-invariant-142' $same "invariant iteration $i failed: policy=$($policy.decision)" }
 if($report.executed_cases -ne $Cases){throw "Harness executed $($report.executed_cases) cases; expected exactly $Cases."}
 $report.status='PASS'
}catch{if($report.failures.Count -eq 0){$report.failures += [ordered]@{category='harness';case=$report.executed_cases+1;detail=$_.Exception.Message}};$report.status='FAIL';$report.evidence.exception_type=$_.Exception.GetType().FullName;$report.evidence.exception=$_.Exception.Message;$report.evidence.stack=$_.ScriptStackTrace;Write-Host "COMPATIBILITY 1000 FAIL: $($_.Exception.Message)"}
finally{StopProc ([ref]$baselineProcess);StopProc ([ref]$candidateProcess);$finalHash=if(Test-Path $candidateConfigPath){(Get-FileHash $candidateConfigPath -Algorithm SHA256).Hash}else{'MISSING'};$report.evidence.production_config_sha256_before=$candidateConfigHash;$report.evidence.production_config_sha256_after=$finalHash;$report.finished_utc=[DateTime]::UtcNow.ToString('o');$report|ConvertTo-Json -Depth 30|Set-Content $ReportPath -Encoding UTF8;Remove-Item $TempRoot -Recurse -Force -ErrorAction SilentlyContinue}
if($report.status -ne 'PASS'){exit 1};Write-Host "COMPATIBILITY 1000 PASS: executed=$($report.executed_cases)";exit 0
