# Untrapped Ultra Mode - health / self-healing diagnostic
# Checks Untrapped, IP/network health, browsers, and policy state.
# Automatic repair is limited to Untrapped-owned files/processes. It does not rewrite Windows networking.
$ErrorActionPreference='Continue'
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$ConfigPath=Join-Path $Root 'config.json';$ReportPath=Join-Path $Root 'diagnostic-latest.txt';$OverridePath=Join-Path $Root 'override-until.txt';$PacketPath=Join-Path $Root 'packet-filter.ps1';$SelfRepairPath=Join-Path $Root 'self-repair.ps1'
$UpdateUrl='https://raw.githubusercontent.com/mehdishah5372-hue/Untrapped/main/ultra-mode/status-untrapped.ps1'
$lines=New-Object System.Collections.Generic.List[string];$problems=New-Object System.Collections.Generic.List[string]
function Report([string]$x){Write-Host $x;[void]$lines.Add($x)};function Problem([string]$x){[void]$problems.Add($x)}
function IP([string]$label,[string]$addr,[string]$kind){if([string]::IsNullOrWhiteSpace($addr)){Report "[WARN MISSING] IP: $label has no address";return};try{[void][Net.IPAddress]::Parse($addr);Report "[OK VALID] IP: $label = $addr ($kind)"}catch{Report "[FAIL INVALID] IP: $label = $addr";Problem "Invalid IP address: $label"}}
function DNS([string]$name){try{@(Resolve-DnsName $name -DnsOnly -ErrorAction Stop|Where-Object IPAddress).Count -gt 0}catch{return $false}}
function Repair-Untrapped{
  if(Test-Path $SelfRepairPath){try{Report '[REPAIR] Running Untrapped self-repair engine.';Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$SelfRepairPath) -WorkingDirectory $Root -Verb RunAs -Wait -WindowStyle Hidden -ErrorAction Stop;Report '[OK REPAIR] Self-repair engine completed.';return}catch{Report '[FAIL REPAIR] Self-repair engine could not be started.'}}
  if(Test-Path $PacketPath){try{@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object CommandLine -like '*packet-filter.ps1*')|ForEach-Object{Stop-Process $_.ProcessId -Force -ErrorAction SilentlyContinue};Start-Sleep -Milliseconds 500;Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$PacketPath) -WorkingDirectory $Root -Verb RunAs -WindowStyle Hidden -ErrorAction Stop;Report '[OK REPAIR] Packet filter restarted.'}catch{Report '[FAIL REPAIR] Packet filter restart failed.';Problem 'Untrapped packet filter could not be restarted.'}}
}
function Browser-Test([string]$name,[string]$exe,[string]$url){
  $p=@(Get-Process -Name $name -ErrorAction SilentlyContinue);if($p.Count){Report "[OK RUNNING] Browser: $name process running ($($p.Count) process(es))"}else{Report "[INFO NOT RUNNING] Browser: $name is not currently running"}
  try{[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;$r=Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 15 -Headers @{'User-Agent'='Mozilla/5.0'} -ErrorAction Stop;if($r.StatusCode -ge 200 -and $r.StatusCode -lt 400){Report "[OK HTTP] Browser-network test for ${name}: $url -> HTTP $($r.StatusCode)";return $true};Report "[FAIL HTTP] Browser-network test for ${name} returned HTTP $($r.StatusCode)";return $false}catch{Report "[FAIL HTTP] Browser-network test for ${name} failed: $($_.Exception.Message)";Problem "$name browser-network path failed.";return $false}
}
Report '';Report '============================================================';Report ' UNTRAPPED ULTRA MODE - HEALTH / SELF-HEALING DIAGNOSTIC';Report '============================================================'
$now=Get-Date;Report "Time: $($now.ToString('yyyy-MM-dd HH:mm:ss zzz'))";Report "Time zone: $([TimeZoneInfo]::Local.DisplayName) ($([TimeZoneInfo]::Local.Id))";Report "UTC: $($now.ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC'))"
Report '';Report 'FILES / CONFIG';Report '-------------';foreach($n in @('WinDivert.dll','WinDivert64.sys','config.json','packet-filter.ps1','ultra-mode.ps1','status-untrapped.ps1','self-repair.ps1')){if(Test-Path (Join-Path $Root $n)){Report "[OK] File: $n present"}else{Report "[FAIL] File: $n missing";Problem "Missing file: $n"}}
$config=$null;$active=$false;$override=$false
try{$config=Get-Content $ConfigPath -Raw|ConvertFrom-Json;$s=[TimeSpan]::Parse([string]$config.start);$e=[TimeSpan]::Parse([string]$config.end);$t=$now.TimeOfDay;if($s -eq $e){$active=$true}elseif($s -lt $e){$active=$t -ge $s -and $t -lt $e}else{$active=$t -ge $s -or $t -lt $e};Report "[OK] Config parsed; schedule $($config.start) -> $($config.end); scheduled window currently $(if($active){'ACTIVE'}else{'INACTIVE'})"}catch{Report "[FAIL] Config parse/schedule: $($_.Exception.Message)";Problem 'config.json or schedule is invalid.'}
if(Test-Path $OverridePath){try{$u=[DateTime]::Parse((Get-Content $OverridePath -Raw)).ToUniversalTime();$override=[DateTime]::UtcNow -lt $u;Report "[INFO] Override: $(if($override){"ACTIVE until $($u.ToString('u'))"}else{'inactive'})"}catch{Report '[WARN] Override file could not be parsed';Problem 'Override file is malformed.'}}else{Report '[INFO] Override: inactive'}
$packet=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object CommandLine -like '*packet-filter.ps1*');$control=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object CommandLine -like '*ultra-mode.ps1*');if($packet.Count){Report '[OK RUNNING] Packet filter: RUNNING'}else{Report '[FAIL NOT RUNNING] Packet filter: NOT RUNNING';Problem 'packet-filter.ps1 is not running.'};if($control.Count){Report '[OK RUNNING] Control plane: RUNNING'}else{Report '[FAIL NOT RUNNING] Control plane: NOT RUNNING';Problem 'ultra-mode.ps1 is not running.'}
Report '';Report 'IP ADDRESS HEALTH';Report '-----------------';try{$ad=@(Get-NetAdapter|Where-Object Status -eq 'Up');foreach($a in $ad){$c=Get-NetIPConfiguration -InterfaceIndex $a.ifIndex -ErrorAction SilentlyContinue;$v4=@($c.IPv4Address|% IPAddress);$v6=@($c.IPv6Address|% IPAddress);if(!$v4.Count -and !$v6.Count){Report "[WARN NO IP] $($a.Name) is UP but has no IP";Problem "$($a.Name) has no IP address."};foreach($x in $v4){IP "$($a.Name) IPv4" $x 'IPv4'};foreach($x in $v6){IP "$($a.Name) IPv6" $x 'IPv6'};if($c.IPv4DefaultGateway){IP "$($a.Name) gateway" ([string]$c.IPv4DefaultGateway.NextHop) 'gateway'};foreach($d in @($c.DnsServer.ServerAddresses)){IP "$($a.Name) DNS" $d 'DNS server'}}}catch{Report "[WARN ERROR] IP query failed: $($_.Exception.Message)";Problem 'Could not inspect local IP configuration.'}
try{$pub=(Invoke-RestMethod 'https://api.ipify.org' -TimeoutSec 10).ToString().Trim();IP 'Public IPv4' $pub 'public IPv4';Report '[OK REACHABLE] Public IPv4 lookup responded.'}catch{Report '[WARN UNAVAILABLE] Public IPv4 lookup failed; local IP may still be fine.'}
try{$pub6=(Invoke-RestMethod 'https://api6.ipify.org' -TimeoutSec 10).ToString().Trim();IP 'Public IPv6' $pub6 'public IPv6'}catch{Report '[INFO] Public IPv6 unavailable.'}
Report '';Report 'DNS / ROUTING / FIREWALL / WFP';Report '-----------------------------';try{$ds=@(Get-DnsClientServerAddress -AddressFamily IPv4|% ServerAddresses|Where-Object {$_});if($ds.Count){Report "[OK CONFIGURED] DNS servers: $($ds -join ', ')"}else{Report '[FAIL] No IPv4 DNS servers configured';Problem 'No IPv4 DNS servers configured.'}}catch{Report '[WARN] DNS configuration query failed'};foreach($n in @('google.com','youtube.com','www.youtube.com','ytimg.com','googlevideo.com','chatgpt.com','crushon.ai','windowsmcp.io')){if(DNS $n){Report "[OK RESOLVED] DNS: $n"}else{Report "[WARN UNRESOLVED] DNS: $n";if($n -eq 'google.com'){Problem 'General DNS resolution failed.'}}}
try{$routes=@(Get-NetRoute -DestinationPrefix '0.0.0.0/0');if($routes.Count){Report "[OK FOUND] IPv4 default routes: $($routes.Count)";foreach($r in $routes){Report "  ifIndex=$($r.ifIndex) NextHop=$($r.NextHop) Metric=$($r.RouteMetric)"}}else{Report '[FAIL NOT FOUND] No IPv4 default route';Problem 'No IPv4 default route.'}}catch{Report '[WARN] Routing query failed'}
try{$profiles=@(Get-NetFirewallProfile);foreach($p in $profiles){if($p.Enabled){Report "[OK ENABLED] Firewall $($p.Name): In=$($p.DefaultInboundAction) Out=$($p.DefaultOutboundAction)"}else{Report "[WARN DISABLED] Firewall $($p.Name)";Problem "Firewall profile $($p.Name) disabled."}};Report "[OK QUERY] Firewall rules visible: $(@(Get-NetFirewallRule).Count)"}catch{Report '[WARN] Firewall query failed'}
try{$bfe=Get-Service BFE;if($bfe.Status -eq 'Running'){Report '[OK RUNNING] WFP Base Filtering Engine (BFE)'}else{Report "[FAIL NOT RUNNING] BFE: $($bfe.Status)";Problem 'BFE is not running.'}}catch{Report '[WARN] BFE query failed'}
Report '';Report 'VPN / ADAPTERS / PROXY / HOSTS';Report '----------------------------';try{$ups=@(Get-NetAdapter|Where-Object Status -eq 'Up');Report "[INFO] Adapters UP: $($ups.Count)";foreach($a in $ups){Report "[OK UP] $($a.Name) | ifIndex=$($a.ifIndex) | $($a.LinkSpeed)"};$vp=@(Get-NetAdapter|Where-Object Name -match '(?i)proton|vpn|wireguard|tun|tap');foreach($v in $vp){Report "[INFO VPN] $($v.Name) | Status=$($v.Status)"}}catch{};try{$h=@(Get-Content 'C:\Windows\System32\drivers\etc\hosts'|Where-Object {$_ -match '(youtube|youtu\.be|ytimg|googlevideo|chatgpt|crushon)' -and $_ -notmatch '^\s*#'});if(!$h.Count){Report '[OK CLEAN] Hosts: no Untrapped target entries'}else{Report "[WARN ENTRIES FOUND] Hosts relevant entries: $($h.Count)";Problem 'Unexpected Untrapped target entries exist in Hosts.'}}catch{};try{$pr=netsh winhttp show proxy 2>&1;Report 'WinHTTP proxy:';$pr|%{Report "  $_"}}catch{}
Report '';Report 'BROWSER HEALTH';Report '--------------';Report 'These are browser-path tests, not claims that a browser UI is open. They check the same HTTPS/DNS path browsers need and look for Untrapped interference.'
$browserResults=@();$browserResults+=Browser-Test 'brave' 'brave.exe' 'https://www.google.com';$browserResults+=Browser-Test 'chrome' 'chrome.exe' 'https://www.google.com';$browserResults+=Browser-Test 'msedge' 'msedge.exe' 'https://www.google.com';$browserResults+=Browser-Test 'firefox' 'firefox.exe' 'https://www.google.com'
try{$tcp=Test-NetConnection 'www.google.com' -Port 443 -WarningAction SilentlyContinue;if($tcp.TcpTestSucceeded){Report "[OK HTTPS] General HTTPS path works; RemoteAddress=$($tcp.RemoteAddress)"}else{Report "[FAIL HTTPS] General HTTPS path failed; RemoteAddress=$($tcp.RemoteAddress)";Problem 'General HTTPS path failed.'}}catch{Report '[WARN] General HTTPS test errored'}
Report '';Report 'POLICY / ACTUAL BLOCKING';Report '-----------------------';$scheduled=[bool]$config.enabled -and $active -and -not $override;Report "[INFO] YouTube + ChatGPT SHOULD be $(if($scheduled){'BLOCKED'}else{'ALLOWED'}) right now.";function BlockTest([string]$n,[bool]$blocked){try{$x=Test-NetConnection $n -Port 443 -WarningAction SilentlyContinue;if($x.TcpTestSucceeded){if($blocked){Report "[FAIL REACHABLE] $n reachable; expected BLOCKED; IP=$($x.RemoteAddress)";Problem "$n is reachable while it should be blocked.";return $false}else{Report "[OK REACHABLE] $n reachable; expected ALLOWED; IP=$($x.RemoteAddress)";return $true}}else{if($blocked){Report "[OK UNREACHABLE] $n unreachable as expected; IP=$($x.RemoteAddress)";return $true}else{Report "[FAIL UNREACHABLE] $n unreachable but should be ALLOWED; IP=$($x.RemoteAddress)";Problem "$n is unreachable while it should be allowed.";return $false}}}catch{Report "[WARN] Block test $n errored";return !$blocked}}
$yt=BlockTest 'www.youtube.com' $scheduled;$ch=BlockTest 'chatgpt.com' $scheduled;$cr=BlockTest 'www.crushon.ai' $true
if(($scheduled -and (!$yt -or !$ch)) -or (!$scheduled -and (!$yt -or !$ch))){Report '[REPAIR NEEDED] Untrapped policy does not match actual YouTube/ChatGPT state.';Repair-Untrapped}else{Report '[OK POLICY MATCH] YouTube/ChatGPT state matches policy.'}
if($browserResults -contains $false -or ($problems|Where-Object {$_ -match 'General HTTPS|DNS resolution|route|IP address|BFE|Firewall|browser-network'}).Count){Report '[REPAIR REVIEW] A checked subsystem is not OK.';Report '[INFO] Automatic repair is deliberately limited to Untrapped-owned files/processes. Windows Firewall/WFP/DNS/routing/VPN/Hosts/browser installations are not rewritten automatically.'}
Report '';Report '============================================================';Report ' WHAT EVERYTHING MEANS - QUICK REFERENCE';Report '============================================================';Report 'IP addresses       | Local/public addresses | Valid + assigned to needed adapters';Report 'Gateway/routes     | Where packets leave    | Valid gateway + default route';Report 'DNS                | Names -> IPs           | DNS servers configured + domains resolve';Report 'HTTPS/browser path | Browser-style web path | Google HTTPS succeeds';Report 'Browser process     | Browser currently open | RUNNING is informational, not required';Report 'Firewall            | Windows firewall       | Profiles enabled + query works';Report 'WFP/BFE            | Windows packet platform| BFE RUNNING';Report 'VPN/adapters        | Network tunnels         | Required adapter(s) UP';Report 'Hosts/proxy         | Local overrides         | No unexpected target entries';Report 'Untrapped filter   | YouTube/ChatGPT dropper| RUNNING + policy tests match';Report 'Control plane      | Schedule/override      | RUNNING';Report 'Override           | Intentional bypass     | Active only when intentionally used';Report '';Report 'STATUS KEY';Report 'OK                 = Healthy/expected.';Report 'INFO               = Informational, not a fault.';Report 'WARN               = Something unusual or unavailable; investigate.';Report 'FAIL               = Expected function/state failed.';Report 'REPAIR NEEDED      = Untrapped detected its own policy mismatch and attempted repair.';Report 'IP HEALTH: OK VALID = valid address; WARN NO IP = UP adapter without an address; FAIL INVALID = malformed address.';Report 'BROWSER HEALTH: OK HTTP = HTTPS web path works; FAIL HTTP = web path failed and may explain browser/search failure.'
Report '';Report '============================================================';Report ' DIAGNOSIS';Report '============================================================';$u=@($problems|Sort-Object -Unique);if(!$u.Count){Report '[HEALTHY] No obvious Untrapped/network/browser-path fault detected.'}else{$u|%{Report "[CAUSE] $_"}};Report '';Report 'Automatic changes made by this diagnostic are limited to restarting/repairing Untrapped itself. It does not alter Windows Firewall, WFP, DNS, routing, VPN, Hosts, proxy, or browser installations.'
$lines|Set-Content $ReportPath -Encoding UTF8;try{Start-Process notepad.exe -ArgumentList $ReportPath -ErrorAction SilentlyContinue}catch{}
