# UARD (Untrapped Auto-Repair Diagnostic) ver 1.0.0 - TRUE BASELINE
$ErrorActionPreference='SilentlyContinue'
$UARDName='UARD (Untrapped Auto-Repair Diagnostic)';$UARDVersion='1.0.0';$Root=Split-Path -Parent $MyInvocation.MyCommand.Path;$Parent=Split-Path -Parent $Root;$ReportPath=Join-Path $Root 'diagnostic-latest.txt';$Repo='https://raw.githubusercontent.com/mehdishah5372-hue/Untrapped/main/';$SelfRepair=Join-Path $Root 'self-repair.ps1'
$core=@('config.json','packet-filter.ps1','self-repair.ps1','status-untrapped.ps1','ultra-mode.ps1');$ext=@('manifest.json','background.js','content.js','popup.html','popup.js','bootstrap.bundle.min.js');$lines=New-Object 'System.Collections.Generic.List[string]';$problems=New-Object 'System.Collections.Generic.List[string]';$update='UNKNOWN';$repair='NOT RUN'
function Log([string]$x){$s='['+(Get-Date -Format HH:mm:ss)+'] '+$x;Write-Host $s;[void]$lines.Add($s)}
function Hash([byte[]]$b){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($b))).Replace('-','').ToLower()}finally{$h.Dispose()}}
function Remote([string]$p){try{$r=Invoke-WebRequest ($Repo+$p+'?cb='+[DateTime]::UtcNow.Ticks) -UseBasicParsing -TimeoutSec 30 -ErrorAction Stop;[Text.Encoding]::UTF8.GetBytes([string]$r.Content)}catch{$null}}
function Same([string]$p,[string]$l){if(!(Test-Path -LiteralPath $l)){return $false};$r=Remote $p;if($null-eq$r){return $null};try{(Hash ([IO.File]::ReadAllBytes($l))) -eq (Hash $r)}catch{$false}}
function HTTPS([string]$h){try{(Test-NetConnection $h -Port 443 -WarningAction SilentlyContinue).TcpTestSucceeded}catch{$false}}
function BraveCopies{$o=@();$u=Join-Path $env:LOCALAPPDATA 'BraveSoftware\Brave-Browser\User Data';if(Test-Path $u){foreach($p in Get-ChildItem $u -Directory -ErrorAction SilentlyContinue|?{$_.Name -eq 'Default' -or $_.Name -like 'Profile *'}){foreach($v in Get-ChildItem (Join-Path $p.FullName Extensions) -Directory -Recurse -ErrorAction SilentlyContinue){foreach($z in Get-ChildItem $v.FullName -Directory -ErrorAction SilentlyContinue){$m=Join-Path $z.FullName manifest.json;if(Test-Path $m){try{if((Get-Content $m -Raw|ConvertFrom-Json).name -eq 'Untrapped'){$o+=$z.FullName}}catch{}}}}}};return @($o|Sort-Object -Unique)}
function Check{
 Log '[POLICY] Reading config, schedule and override.';$c=$null;$scheduled=$false;$override=$false;try{$c=Get-Content (Join-Path $Root config.json) -Raw|ConvertFrom-Json;$a=[TimeSpan]::Parse($c.start);$b=[TimeSpan]::Parse($c.end);$n=(Get-Date).TimeOfDay;$inside=if($a -lt $b){$n-ge$a-and$n-lt$b}else{$n-ge$a-or$n-lt$b};$o=Join-Path $Root override-until.txt;if(Test-Path $o){try{$override=[DateTime]::UtcNow -lt ([DateTime]::Parse((Get-Content $o -Raw)).ToUniversalTime()}catch{[void]$problems.Add('Override file is unreadable.')}};$scheduled=[bool]($c.enabled-and$inside-and-not$override);Write-Host ('[STATUS] Policy: '+$(if($c.enabled){'ENABLED'}else{'DISABLED'}));Write-Host ('[STATUS] Schedule: '+$c.start+' - '+$c.end);Write-Host ('[STATUS] Scheduled blocking: '+$(if($scheduled){'ACTIVE'}else{'INACTIVE'}));Write-Host ('[STATUS] Override: '+$(if($override){'ACTIVE'}else{'INACTIVE'}))}catch{[void]$problems.Add('Config is invalid or unreadable.')}
 Log '[POLICY] Checking actual target reachability.';$yt=HTTPS 'www.youtube.com';$ch=HTTPS 'chatgpt.com';$cr=HTTPS 'www.crushon.ai';$want=-not$scheduled;Write-Host ('[STATUS] YouTube: '+$(if($yt){'REACHABLE'}else{'BLOCKED'}));Write-Host ('[STATUS] ChatGPT: '+$(if($ch){'REACHABLE'}else{'BLOCKED'}));Write-Host ('[STATUS] CrushOn: '+$(if($cr){'REACHABLE'}else{'BLOCKED'}));if($c){if($yt-ne$want){[void]$problems.Add('YouTube does not match configured policy.')};if($ch-ne$want){[void]$problems.Add('ChatGPT does not match configured policy.')};if($cr){[void]$problems.Add('CrushOn is reachable despite always-block policy.')}}
 Log '[CORE] Checking canonical Untrapped source.';$bad=@();$unknown=@();foreach($f in$core){$x=Same ('ultra-mode/'+$f) (Join-Path $Root $f);if($x-eq$false){$bad+=$f}elseif($null-eq$x){$unknown+=$f}};if($bad.Count){[void]$problems.Add('Untrapped core differs from canonical GitHub: '+($bad-join ', '))};Write-Host ('[STATUS] Core: '+$(if($bad.Count){'MISMATCH'}elseif($unknown.Count){'UNVERIFIED'}else{'CURRENT'}))
 foreach($f in 'WinDivert.dll','WinDivert64.sys'){if(!(Test-Path (Join-Path $Root $f))){[void]$problems.Add('Required native file missing: '+$f)}};Write-Host ('[STATUS] Native files: '+$(if((Test-Path (Join-Path $Root WinDivert.dll))-and(Test-Path (Join-Path $Root WinDivert64.sys))){'PRESENT'}else{'MISSING'}))
 $packet=@(Get-CimInstance Win32_Process|?{$_.CommandLine-like'*packet-filter.ps1*'});$control=@(Get-CimInstance Win32_Process|?{$_.CommandLine-like'*ultra-mode.ps1*'});Write-Host ('[STATUS] Packet filter: '+$(if($packet.Count){'RUNNING'}else{'STOPPED'}));Write-Host ('[STATUS] Control plane: '+$(if($control.Count){'RUNNING'}else{'STOPPED'}));if(!$packet.Count){[void]$problems.Add('Packet filter is not running.')};if(!$control.Count){[void]$problems.Add('Control plane is not running.')}
 Log '[EXTENSION] Checking canonical extension source.';$ebad=@();$eunknown=@();foreach($f in$ext){$x=Same $f (Join-Path $Parent $f);if($x-eq$false){$ebad+=$f}elseif($null-eq$x){$eunknown+=$f}};if($ebad.Count){[void]$problems.Add('Enhanced extension source differs from canonical GitHub: '+($ebad-join ', '))};Write-Host ('[STATUS] Extension source: '+$(if($ebad.Count){'MISMATCH'}elseif($eunknown.Count){'UNVERIFIED'}else{'CURRENT'}))
 Log '[BRAVE] Checking installed packaged copy.';$bc=BraveCopies;Write-Host ('[STATUS] Brave Untrapped copies: '+$bc.Count+' '+$(if($bc.Count){'FOUND'}else{'NOT FOUND - INFORMATIONAL'}));if($bc.Count){foreach($d in$bc){$bb=@();foreach($f in$ext){if((Same $f (Join-Path $d $f))-eq$false){$bb+=$f}};if($bb.Count){[void]$problems.Add('Installed Brave Untrapped differs from canonical GitHub: '+($bb-join ', '))}}}
 Log '[NETWORK] Checking DNS, HTTPS, Hosts, proxy and BFE.';$dns=$false;try{$dns=@(Resolve-DnsName google.com -DnsOnly -ErrorAction Stop|? IPAddress).Count-gt 0}catch{};$goo=HTTPS 'www.google.com';$bfe=$false;try{$bfe=(Get-Service BFE).Status-eq'Running'}catch{};$hp=Join-Path $env:SystemRoot 'System32\drivers\etc\hosts';$hosts=@();if(Test-Path $hp){$hosts=@(Get-Content $hp|?{$_-match'(?i)(youtube|youtu\.be|chatgpt|crushon)'-and$_-notmatch'^\s*#'})};Write-Host ('[STATUS] DNS: '+$(if($dns){'OK'}else{'FAILED'}));Write-Host ('[STATUS] Google HTTPS: '+$(if($goo){'OK'}else{'FAILED'}));Write-Host ('[STATUS] Relevant Hosts: '+$hosts.Count);Write-Host ('[STATUS] BFE: '+$(if($bfe){'RUNNING'}else{'NOT RUNNING/UNKNOWN'}));if(!$dns){[void]$problems.Add('External DNS resolution is failing.')};if(!$goo){[void]$problems.Add('External HTTPS connectivity to Google is failing.')};if($hosts.Count){[void]$problems.Add('Relevant Hosts entries were found.')};if(!$bfe){[void]$problems.Add('Base Filtering Engine is not running.')}
 return @{Problems=@($problems);CoreBad=$bad;CoreUnknown=$unknown;ExtBad=$ebad;ExtUnknown=$eunknown;Brave=$bc;Packet=$packet;Control=$control;Dns=$dns;Google=$goo;Hosts=$hosts;Bfe=$bfe}}
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;Log "[START] === $UARDName ver $UARDVersion ===";Log '[UPDATE] Checking canonical GitHub version.';try{$r=Remote 'ultra-mode/status-untrapped.ps1';if($null-eq$r){$update='UNVERIFIED'}elseif((Hash ([IO.File]::ReadAllBytes($MyInvocation.MyCommand.Path)))-eq(Hash $r)){$update='ALREADY CURRENT';Log '[UPDATE] No update needed.'}else{$tmp=$MyInvocation.MyCommand.Path+'.tmp';[IO.File]::WriteAllBytes($tmp,$r);Move-Item $tmp $MyInvocation.MyCommand.Path -Force;$update='UPDATED';Log '[UPDATE] Updated successfully; continuing current run.'}}catch{$update='UNVERIFIED';Log '[UPDATE] Could not verify canonical version.'}
$before=Check;if($before.Problems.Count){Log ('[AUTO-REPAIR] '+$before.Problems.Count+' issue(s) detected. Starting UARD.');$p=Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$SelfRepair) -Verb RunAs -WorkingDirectory $Root -PassThru -WindowStyle Normal -ErrorAction SilentlyContinue;if($p){$p.WaitForExit();$repair=if($p.ExitCode-eq0){'SUCCESS'}elseif($p.ExitCode-eq2){'VERIFICATION UNKNOWN'}else{'FAILURE'};Log ('[AUTO-REPAIR] UARD exit code '+$p.ExitCode+' / '+$repair)}else{$repair='START FAILURE';[void]$problems.Add('UARD could not be started.')};Log '[VERIFY] Running post-repair verification.';$after=Check}else{$repair='NOT NEEDED';$after=$before;Log '[AUTO-REPAIR] No repair required.'}
if($repair-eq'SUCCESS'){$remaining=@($after.Problems|?{$_-notlike'Untrapped core differs from canonical GitHub:*'-and$_-notlike'Enhanced extension source differs from canonical GitHub:*'})}else{$remaining=@($after.Problems)}
$overall=if($remaining.Count){'UNHEALTHY'}else{'HEALTHY'};$out=@('CONDENSED DIAGNOSIS',' OVERALL: '+$overall,' Auto-update: '+$update,' Auto-repair: '+$repair,' Remaining problems: '+$remaining.Count);foreach($p in$remaining){$out+=' ! '+$p};$out+=('');$out+=('DETAILED DIAGNOSIS');$out+=(' Core source: '+$(if($repair-eq'SUCCESS'){'REPAIRED + VERIFIED'}elseif($after.CoreBad.Count){'MISMATCH'}elseif($after.CoreUnknown.Count){'UNVERIFIED'}else{'CURRENT'}));$out+=(' Extension source: '+$(if($repair-eq'SUCCESS'){'REPAIRED + VERIFIED'}elseif($after.ExtBad.Count){'MISMATCH'}elseif($after.ExtUnknown.Count){'UNVERIFIED'}else{'CURRENT'}));$out+=(' Brave copies: '+$after.Brave.Count+' (0 = informational only)');$out+=(' Packet filter: '+$(if($after.Packet.Count){'RUNNING'}else{'STOPPED'}));$out+=(' Control plane: '+$(if($after.Control.Count){'RUNNING'}else{'STOPPED'}));$out+=(' DNS: '+$(if($after.Dns){'OK'}else{'FAILED'}));$out+=(' Google HTTPS: '+$(if($after.Google){'OK'}else{'FAILED'}));$out+=(' Hosts: '+$after.Hosts.Count);$out+=(' BFE: '+$(if($after.Bfe){'RUNNING'}else{'NOT RUNNING/UNKNOWN'}));$out+=('');$out+=('EXPLANATORY TABLE');$out+=('Component | Check | Action');$out+=('Core | SHA-256 vs canonical | UARD repairs + verifies');$out+=('Extension | SHA-256 vs canonical | UARD repairs + verifies');$out+=('Brave copy absent | Detection | INFORMATIONAL ONLY');$out+=('Policy | Schedule/override/reachability | Diagnose + UARD');$out+=('Network | DNS/HTTPS/Hosts/BFE/topology | Diagnose only');$out+=('');$out+=('VERSION / BASELINE');$out+=('Name: '+$UARDName);$out+=('Version: '+$UARDVersion);$out+=('TRUE BASELINE: 1.0.0');$out+=('');$out+=('DIAGNOSTIC CONTRACT');$out+=('UARD success is authoritative for source components it repaired and verified.');$out+=('Windows Firewall/WFP/DNS/routes/Hosts/proxy/adapters/VPN/override policy are never automatically modified.');$all=@($lines)+@('')+$out;try{$all|Set-Content $ReportPath -Encoding UTF8}catch{};Write-Host '';Write-Host ('================ '+$UARDName+' ver '+$UARDVersion+' ================');$out|%{Write-Host $_};Write-Host ('Report: '+$ReportPath);try{Start-Process -FilePath 'notepad.exe' -ArgumentList @($ReportPath) -ErrorAction Stop;Write-Host '[REPORT] diagnostic-latest.txt opened in Notepad.'}catch{Write-Host ('[REPORT] Notepad could not be opened: '+$_.Exception.Message)}