# Untrapped Ultra Mode - Baseline Health Diagnostic
# READ-ONLY. Observes Untrapped, Brave, Windows networking and policy state.
# Never changes firewall/WFP/DNS/routes/Hosts/proxy/adapters/VPN/override.
$ErrorActionPreference='SilentlyContinue'
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$Parent=Split-Path -Parent $Root
$ReportPath=Join-Path $Root 'diagnostic-latest.txt'
$RepoBase='https://raw.githubusercontent.com/mehdishah5372-hue/Untrapped/main/'
$ExtensionFiles=@('manifest.json','background.js','content.js','popup.html','popup.js','bootstrap.bundle.min.js')
$CoreTextFiles=@('config.json','packet-filter.ps1','ultra-mode.ps1','status-untrapped.ps1','self-repair.ps1')
$Lines=New-Object 'System.Collections.Generic.List[string]'
$Problems=New-Object 'System.Collections.Generic.List[string]'
$Status=New-Object 'System.Collections.Generic.List[string]'
function Trace([string]$Stage,[string]$Message){$line='['+(Get-Date -Format 'HH:mm:ss')+'] ['+$Stage+'] '+$Message;Write-Host $line;[void]$Lines.Add($line)}
function Problem([string]$Message){if($Message -and -not($Problems -contains $Message)){[void]$Problems.Add($Message)}}
function StatusLine([string]$Name,[string]$Value){$line=('{0}: {1}' -f $Name,$Value);[void]$Status.Add($line);Trace 'STATUS' $line}
function RemoteText([string]$Path){Trace 'GITHUB' ('Checking canonical '+$Path);$r=Invoke-WebRequest -Uri ($RepoBase+$Path+'?cb='+[DateTime]::UtcNow.Ticks) -UseBasicParsing -TimeoutSec 30 -ErrorAction Stop;return [string]$r.Content}
function SameCanonical([string]$RemotePath,[string]$LocalPath){if(-not(Test-Path -LiteralPath $LocalPath)){return $false};try{return ((RemoteText $RemotePath)-ceq([IO.File]::ReadAllText($LocalPath)))}catch{Trace 'ERROR' ('Comparison failed: '+$RemotePath);return $false}}
function Https([string]$HostName){try{return [bool](Test-NetConnection -ComputerName $HostName -Port 443 -WarningAction SilentlyContinue).TcpTestSucceeded}catch{return $false}}
function Find-BraveUntrapped{$out=@();$ud=Join-Path $env:LOCALAPPDATA 'BraveSoftware\Brave-Browser\User Data';if(-not(Test-Path -LiteralPath $ud)){return @()};foreach($p in @(Get-ChildItem -LiteralPath $ud -Directory|Where-Object{$_.Name -eq 'Default' -or $_.Name -like 'Profile *'})){ $ed=Join-Path $p.FullName 'Extensions';if(-not(Test-Path -LiteralPath $ed)){continue};foreach($id in @(Get-ChildItem -LiteralPath $ed -Directory)){foreach($v in @(Get-ChildItem -LiteralPath $id.FullName -Directory)){ $m=Join-Path $v.FullName 'manifest.json';if(Test-Path -LiteralPath $m){try{if(([string](Get-Content -LiteralPath $m -Raw|ConvertFrom-Json).name)-eq 'Untrapped'){$out+=$v.FullName}}catch{}}}}};return @($out|Sort-Object -Unique)}
function WriteReport{$Lines|Set-Content -LiteralPath $ReportPath -Encoding UTF8}
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
Trace 'START' '=== UNTRAPPED SYSTEM-WIDE BASELINE DIAGNOSTIC ==='
$config=$null;$scheduled=$false;$override=$false
Trace 'POLICY' 'Reading configuration, schedule and override.'
try{$config=Get-Content -LiteralPath (Join-Path $Root 'config.json') -Raw|ConvertFrom-Json;$start=[TimeSpan]::Parse([string]$config.start);$end=[TimeSpan]::Parse([string]$config.end);$now=(Get-Date).TimeOfDay;if($start -eq $end){$inWindow=$true}elseif($start -lt $end){$inWindow=($now -ge $start -and $now -lt $end)}else{$inWindow=($now -ge $start -or $now -lt $end)};$of=Join-Path $Root 'override-until.txt';if(Test-Path -LiteralPath $of){try{$until=[DateTime]::Parse((Get-Content -LiteralPath $of -Raw)).ToUniversalTime();$override=([DateTime]::UtcNow -lt $until)}catch{Problem 'Override file exists but is unreadable.'}};$scheduled=[bool]($config.enabled -and $inWindow -and -not $override);StatusLine 'Policy enabled' $config.enabled;StatusLine 'Schedule' ($config.start+' - '+$config.end);StatusLine 'Scheduled blocking active' $scheduled;StatusLine 'Override active' $override}catch{Problem 'Config is invalid or unreadable.'}
Trace 'POLICY' 'Testing actual target reachability.'
$yt=Https 'www.youtube.com';$chat=Https 'chatgpt.com';$crush=Https 'www.crushon.ai';$expected=-not $scheduled
StatusLine 'YouTube actual' $(if($yt){'REACHABLE'}else{'BLOCKED'});StatusLine 'ChatGPT actual' $(if($chat){'REACHABLE'}else{'BLOCKED'});StatusLine 'CrushOn actual' $(if($crush){'REACHABLE'}else{'BLOCKED'})
if($yt -ne $expected){Problem 'YouTube does not match configured policy.'};if($chat -ne $expected){Problem 'ChatGPT does not match configured policy.'};if($crush){Problem 'CrushOn is reachable despite always-block policy.'}
Trace 'CORE' 'Checking processes and canonical source.'
$packet=@(Get-CimInstance Win32_Process|Where-Object{$_.CommandLine -like '*packet-filter.ps1*'});$control=@(Get-CimInstance Win32_Process|Where-Object{$_.CommandLine -like '*ultra-mode.ps1*'});$coreBad=@();$missing=@()
foreach($f in $CoreTextFiles){$p=Join-Path $Root $f;if(-not(Test-Path -LiteralPath $p)){$missing+=$f}elseif(-not(SameCanonical ('ultra-mode/'+$f) $p)){$coreBad+=$f}}
foreach($f in @('WinDivert.dll','WinDivert64.sys')){if(-not(Test-Path -LiteralPath (Join-Path $Root $f))){$missing+=$f}}
StatusLine 'Packet filter process' $(if($packet.Count){'RUNNING'}else{'STOPPED'});StatusLine 'Control plane process' $(if($control.Count){'RUNNING'}else{'STOPPED'});StatusLine 'Core required files' ((7-$missing.Count).ToString()+'/7');StatusLine 'Core canonical mismatches' $(if($coreBad.Count){$coreBad -join ', '}else{'NONE'})
if(-not$packet.Count){Problem 'Packet filter is not running.'};if(-not$control.Count){Problem 'Control plane is not running.'};if($missing.Count){Problem ('Required Untrapped files missing: '+($missing -join ', '))};if($coreBad.Count){Problem ('Untrapped core differs from canonical GitHub: '+($coreBad -join ', '))}
Trace 'EXTENSION' 'Checking Enhanced extension source.';$sourceBad=@();foreach($f in $ExtensionFiles){if(-not(SameCanonical $f (Join-Path $Parent $f))){$sourceBad+=$f}};StatusLine 'Extension source mismatches' $(if($sourceBad.Count){$sourceBad -join ', '}else{'NONE'});if($sourceBad.Count){Problem ('Enhanced extension source differs from canonical GitHub: '+($sourceBad -join ', '))}
Trace 'BRAVE' 'Checking installed Brave extension storage.';$installed=Find-BraveUntrapped;StatusLine 'Installed Brave Untrapped copies' $installed.Count;if(-not$installed.Count){Problem 'Installed Brave Untrapped extension was not found in standard extension storage.'}else{foreach($d in $installed){$bad=@();foreach($f in $ExtensionFiles){if(-not(SameCanonical $f (Join-Path $d $f))){$bad+=$f}};StatusLine ('Brave copy '+$d) $(if($bad.Count){'MISMATCH: '+($bad -join ', ')}else{'CURRENT OK'});if($bad.Count){Problem ('Installed Brave Untrapped differs from canonical GitHub: '+($bad -join ', '))}}}
Trace 'NETWORK' 'Checking Windows network stack and surrounding state.';$adapters=@(Get-NetAdapter|Where-Object{$_.Status -eq 'Up'});$routes=@(Get-NetRoute -DestinationPrefix '0.0.0.0/0');$dnsOK=$false;try{$dnsOK=@(Resolve-DnsName 'google.com' -DnsOnly -ErrorAction Stop|Where-Object{$_.IPAddress}).Count -gt 0}catch{};$google=Https 'www.google.com';$bfe=$false;try{$bfe=(Get-Service BFE).Status -eq 'Running'}catch{};$hosts=Join-Path $env:SystemRoot 'System32\drivers\etc\hosts';$hostHits=@();if(Test-Path -LiteralPath $hosts){$hostHits=@(Get-Content $hosts|Where-Object{$_ -match '(?i)(youtube|youtu\.be|chatgpt|crushon)' -and $_ -notmatch '^\s*#'})};$proxy='UNKNOWN';try{$px=netsh winhttp show proxy 2>$null;if($px -match 'Direct access'){$proxy='DIRECT'}elseif($px -match 'Proxy Server'){$proxy='CONFIGURED'}}catch{};$vpn=@(Get-NetAdapter|Where-Object{$_.Status -eq 'Up' -and $_.InterfaceDescription -match '(?i)vpn|wireguard|tun|tap|proton|speedify|warp|tailscale|openvpn'})
StatusLine 'Active adapters' $adapters.Count;StatusLine 'Default routes' $routes.Count;StatusLine 'VPN/tunnel adapters' $vpn.Count;StatusLine 'DNS google.com' $(if($dnsOK){'OK'}else{'FAILED'});StatusLine 'Google HTTPS' $(if($google){'OK'}else{'FAILED'});StatusLine 'Relevant Hosts entries' $hostHits.Count;StatusLine 'WinHTTP proxy' $proxy;StatusLine 'Base Filtering Engine' $(if($bfe){'RUNNING'}else{'NOT RUNNING/UNKNOWN'});if(-not$dnsOK){Problem 'External DNS resolution is failing.'};if(-not$google){Problem 'External HTTPS connectivity to Google is failing.'};if($hostHits.Count){Problem 'Relevant Hosts entries were found.'};if(-not$bfe){Problem 'Base Filtering Engine is not running.'}
Trace 'DIAGNOSIS' 'Building condensed and detailed diagnosis.'
$overall=if($Problems.Count){'UNHEALTHY'}else{'HEALTHY'};$cond=@();$cond+='CONDENSED DIAGNOSIS';$cond+=(' OVERALL: '+$overall);$cond+=(' PROBLEMS: '+$Problems.Count);if($Problems.Count){foreach($p in $Problems){$cond+=(' ! '+$p)}}else{$cond+=' No detected problems.'};$cond+='';$cond+='DETAILED DIAGNOSIS';$cond+=(' Policy: '+$(if($scheduled){'SCHEDULED BLOCK ACTIVE'}else{'SCHEDULED BLOCK INACTIVE'}));$cond+=(' Override: '+$override);$cond+=(' Core mismatches: '+$(if($coreBad.Count){$coreBad -join ', '}else{'NONE'}));$cond+=(' Extension-source mismatches: '+$(if($sourceBad.Count){$sourceBad -join ', '}else{'NONE'}));$cond+=(' Brave installed copies: '+$installed.Count);$cond+=(' Network: adapters='+$adapters.Count+', default routes='+$routes.Count+', VPN/tunnel='+$vpn.Count);$cond+=(' DNS='+$(if($dnsOK){'OK'}else{'FAILED'})+', Google HTTPS='+$(if($google){'OK'}else{'FAILED'}));$cond+=(' Hosts target entries='+$hostHits.Count+', WinHTTP proxy='+$proxy+', BFE='+$(if($bfe){'RUNNING'}else{'NOT RUNNING/UNKNOWN'}));$cond+='';$cond+='SYSTEM-WIDE STATUS';$cond+=($Status|ForEach-Object{' '+$_});$cond+='';$cond+='DIAGNOSTIC CONTRACT';$cond+=' This diagnostic is observation-only. It does not repair, restart, alter override state, or modify Windows networking.';$cond+=' Every check above is included in this report.';$cond+=''
$cond|ForEach-Object{Trace 'REPORT' $_};$Lines|Set-Content -LiteralPath $ReportPath -Encoding UTF8;Write-Host '';Write-Host ($cond -join [Environment]::NewLine);Write-Host '';Trace 'END' '=== DIAGNOSTIC COMPLETE ==='
