# UAUD Diagnostics 1.2.0 — independent, non-installing verification
$ErrorActionPreference='Stop'
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$PSExe=Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
$Middleman='https://untrapped-update-middleman-000-999-production.up.railway.app'
$ExpectedVersion='3.2.0';$ExpectedProtocol=3;$ExpectedBaseline='1.0.0';$MaxBytes=8388608
$RunId=(Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[Guid]::NewGuid().ToString('N').Substring(0,8)
$Run=Join-Path (Join-Path $Root 'uaud-diagnostics') $RunId
New-Item -ItemType Directory -Force -Path $Run|Out-Null
$EL=Join-Path $Root 'ErrorLibrary.ps1';if(Test-Path $EL){. $EL}
function Stamp([string]$s){Write-Host ('['+(Get-Date -Format HH:mm:ss)+'] '+$s)}
function H([byte[]]$b){$x=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($x.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$x.Dispose()}}
function HF([string]$p){(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function J([string]$n,[object]$o){$o|ConvertTo-Json -Depth 40|Set-Content (Join-Path $Run $n) -Encoding UTF8}
function Scan([string]$src,[string[]]$lines,[int]$rc=0){foreach($l in @($lines)){if([string]::IsNullOrWhiteSpace($l)){continue};if(Get-Command Test-ErrorLike -EA SilentlyContinue){if(Test-ErrorLike $l $rc 0 -and (Get-Command Save-ErrorEvent -EA SilentlyContinue)){[void](Save-ErrorEvent -Source $src -Stream 'diagnostic-output' -Text $l -ExitCode $rc -Context 'independent diagnostic scan')}}}}
function Parse([string]$p){$t=$null;$e=$null;$a=[System.Management.Automation.Language.Parser]::ParseFile($p,[ref]$t,[ref]$e);[pscustomobject]@{ast=$a;errors=@($e)}}
function Child([string]$file,[string[]]$args){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$PSExe;$psi.WorkingDirectory=$Root;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments='-NoLogo -NoProfile -ExecutionPolicy Bypass -File "'+$file+'" '+(($args|ForEach-Object{'"'+$_+'"'})-join ' ');$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$o=$p.StandardOutput.ReadToEnd();$e=$p.StandardError.ReadToEnd();$p.WaitForExit();$ls=@($o -split "`r?`n")+@($e -split "`r?`n");Scan (Split-Path $file -Leaf) $ls $p.ExitCode;[pscustomobject]@{exit_code=$p.ExitCode;stdout=$o;stderr=$e}}
function Fetch([string]$name){$q=[Net.HttpWebRequest]::Create($Middleman+'/v1/artifact/'+$name+'?diagnostic='+$RunId);$q.Method='GET';$q.Timeout=30000;$q.ReadWriteTimeout=30000;$q.AllowAutoRedirect=$false;$r=$q.GetResponse();try{$v=[string]$r.Headers['X-Untrapped-Version'];$p=[int]$r.Headers['X-Untrapped-Protocol'];$b=[string]$r.Headers['X-Untrapped-Baseline'];if($v-ne$ExpectedVersion-or$p-ne$ExpectedProtocol-or$b-ne$ExpectedBaseline){throw "MIDDLEMAN_IDENTITY_MISMATCH version=$v protocol=$p baseline=$b"};if($r.ContentLength -gt $MaxBytes){throw 'RESPONSE_TOO_LARGE'};$s=$r.GetResponseStream();$m=New-Object IO.MemoryStream;$buf=New-Object byte[] 65536;$n=0;try{while(($z=$s.Read($buf,0,$buf.Length))-gt 0){$n+=$z;if($n-gt$MaxBytes){throw 'RESPONSE_TOO_LARGE'};$m.Write($buf,0,$z)};$bytes=$m.ToArray()}finally{$s.Dispose();$m.Dispose()};$hs=[string]$r.Headers['X-Untrapped-SHA256'];if($hs-and$hs-ne(H $bytes)){throw 'SHA256_MISMATCH'};return $bytes}finally{$r.Dispose()}}
Stamp 'UAUD DIAGNOSTICS 1.2.0 — NON-INSTALLING'
Stamp 'UAUD.ps1 and self-repair.ps1 will NOT be executed.'
J 'run.json' ([ordered]@{schema=1;version='1.2.0';run_id=$RunId;install_performed=$false;installer_invoked=$false;middleman=$Middleman;expected_version=$ExpectedVersion;expected_protocol=$ExpectedProtocol;expected_baseline=$ExpectedBaseline})
$files=@('UAUD.ps1','self-repair.ps1','UAUD-validate.ps1','sandbox-behaviour.ps1','evidence.ps1','ErrorLibrary.ps1','packet-filter.ps1','artifact-schema.json','config.json')
Stamp 'GATE 1 — required files and PowerShell parsing'
$checks=@();foreach($f in $files){$p=Join-Path $Root $f;if(-not(Test-Path $p)){$checks+=[ordered]@{file=$f;pass=$false;error='FILE_MISSING'};continue};if($f.EndsWith('.ps1')){$r=Parse $p;$checks+=[ordered]@{file=$f;pass=(@($r.errors).Count-eq0);errors=@($r.errors|ForEach-Object{[ordered]@{message=$_.Message;line=$_.Extent.StartLineNumber;column=$_.Extent.StartColumnNumber}});sha256=HF $p}}else{$checks+=[ordered]@{file=$f;pass=$true;sha256=HF $p}}};J 'file-check.json' $checks;if(@($checks|Where-Object{-not$_.pass}).Count){Stamp 'FAIL — file/parser gate';exit 1};Stamp 'PASS — all required files present and parseable'
Stamp 'GATE 2 — ErrorLibrary contract'
$fn=@('Get-ErrorFingerprint','Classify-ErrorText','Test-ErrorLike','Save-ErrorEvent','Scan-ErrorOutput');$fc=@($fn|ForEach-Object{[ordered]@{name=$_;present=([bool](Get-Command $_ -EA SilentlyContinue))}});J 'error-library-check.json' ([ordered]@{pass=(@($fc|Where-Object{-not$_.present}).Count-eq0);functions=$fc;persistent_path=(Join-Path $Root 'error-library.jsonl')});if(@($fc|Where-Object{-not$_.present}).Count){Stamp 'FAIL — ErrorLibrary contract';exit 1};Stamp 'PASS — output scanner and persistent error library available'
Stamp 'GATE 3 — pinned 000-999 middleman'
try{$hb=Fetch 'ultra-mode/config.json';$pb=Fetch 'ultra-mode/packet-filter.ps1';J 'middleman-health.json' ([ordered]@{pass=$true;version=$ExpectedVersion;protocol=$ExpectedProtocol;baseline=$ExpectedBaseline;config_sha256=H $hb;packet_filter_sha256=H $pb});Stamp 'PASS — pinned artifacts fetched with redirect rejection, identity and size/hash validation'}catch{$msg=$_.Exception.Message;J 'middleman-health.json' ([ordered]@{pass=$false;error=$msg;fingerprint=(H ([Text.Encoding]::UTF8.GetBytes($msg)))});Stamp "FAIL — middleman: $msg";exit 1}
Stamp 'GATE 4 — canonical policy sanity'
$cfg=Get-Content (Join-Path $Root 'config.json') -Raw|ConvertFrom-Json;$ok=($cfg.enabled-eq$true-and[string]$cfg.start-eq'05:00'-and[string]$cfg.end-eq'22:00'-and@($cfg.domains)-contains'youtube.com'-and@($cfg.domains)-contains'chatgpt.com'-and@($cfg.alwaysBlockedDomains)-contains'crushon.ai'-and@($cfg.alwaysAllowedDomains)-contains'windowsmcp.io');J 'canonical-config-check.json' ([ordered]@{pass=$ok});if(-not$ok){Stamp 'FAIL — canonical policy mismatch';exit 1};Stamp 'PASS — canonical policy shape verified'
Stamp 'GATE 5 — syntax validator child execution with full stdout/stderr capture'
$tmp=Join-Path $env:TEMP ('uaud-diagnostic-'+$RunId+'.ps1');Set-Content $tmp '$x = @{ Enabled = $true; Start = ''05:00''; End = ''22:00'' }' -Encoding UTF8;try{$vr=Child (Join-Path $Root 'UAUD-validate.ps1') @('-Candidate',$tmp,'-Artifact','diagnostic-candidate.ps1')}finally{Remove-Item $tmp -Force -EA SilentlyContinue};if($vr.exit_code-ne0){Stamp "FAIL — validator exit=$($vr.exit_code)";exit 1};Stamp 'PASS — validator gate'
Stamp 'GATE 6 — behavioural helper sandbox'
$br=Child (Join-Path $Root 'sandbox-behaviour.ps1') @();if($br.exit_code-ne0){Stamp "FAIL — behavioural sandbox exit=$($br.exit_code)";exit 1};Stamp 'PASS — behavioural sandbox'
Stamp 'GATE 7 — protected-boundary audit (only destructive configuration mutations are forbidden here)'
$bad=@('Set-NetFirewallRule','New-NetFirewallRule','Remove-NetFirewallRule','Set-DnsClientServerAddress','route.exe','netsh.exe');$viol=@();foreach($f in @('UAUD.ps1','UAUD-validate.ps1','sandbox-behaviour.ps1','self-repair.ps1')){$t=Get-Content (Join-Path $Root $f) -Raw;foreach($k in $bad){if($t -match [regex]::Escape($k)){$viol+=[ordered]@{file=$f;keyword=$k}}}};J 'boundary-audit.json' ([ordered]@{pass=(@($viol).Count-eq0);violations=$viol});if(@($viol).Count){Stamp 'FAIL — forbidden Windows configuration mutation reference found';exit 1};Stamp 'PASS — protected Windows configuration boundaries clean'
J 'result.json' ([ordered]@{schema=1;status='PASS';install_performed=$false;uaud_executed=$false;self_repair_executed=$false;message='All independent diagnostics passed. This diagnostic intentionally does not certify an installer run.';timestamp_utc=[DateTime]::UtcNow.ToString('o');report=$Run})
Stamp 'RESULT: PASS — independent diagnostics complete; nothing was installed.'
Stamp "REPORT: $Run"
exit 0
