# UAUD validation engine 1.0.1
# Syntax gate + adaptive repair + ErrorLibrary. Candidate is NEVER executed here.
$ErrorActionPreference='Stop'
param(
 [Parameter(Mandatory=$true)][string]$Candidate,
 [string]$Canonical,
 [string]$Artifact='candidate.ps1',
 [int]$RepeatedErrorThreshold=5,
 [int]$MaxAttempts=50,
 [int]$EmergencyCeiling=200
)
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$ErrorLibrary=Join-Path $Root 'ErrorLibrary.ps1'
if(Test-Path -LiteralPath $ErrorLibrary){. $ErrorLibrary}
$ReportDir=Join-Path $Root 'uaud-reports';New-Item -ItemType Directory -Path $ReportDir -Force|Out-Null
function Write-Event([string]$Message){Write-Host ('[UAUD '+(Get-Date -Format HH:mm:ss)+'] '+$Message)}
function Hash-Text([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Get-ParserResult([string]$Source){$tokens=$null;$errors=$null;$ast=[System.Management.Automation.Language.Parser]::ParseInput($Source,[ref]$tokens,[ref]$errors);if(@($errors).Count -eq 0){return [pscustomobject]@{pass=$true;errors=@();ast=$ast}};[pscustomobject]@{pass=$false;errors=@($errors|ForEach-Object{[ordered]@{message=$_.Message;line=$_.Extent.StartLineNumber;column=$_.Extent.StartColumnNumber;end_line=$_.Extent.EndLineNumber;end_column=$_.Extent.EndColumnNumber}});ast=$ast}}
function Invoke-DeterministicRepair([string]$Source,[object]$ParserResult){$out=$Source;foreach($e in @($ParserResult.errors)){if($e.message -match '(?i)missing.*closing.*brace'){$out=$out.TrimEnd()+"`n}"}elseif($e.message -match '(?i)missing.*closing.*parenthesis'){$out=$out.TrimEnd()+"`n)"}elseif($e.message -match '(?i)missing.*closing.*bracket'){$out=$out.TrimEnd()+"`n]"}else{return [pscustomobject]@{changed=$false;source=$Source;action='NO_SAFE_DETERMINISTIC_REPAIR'}}};[pscustomobject]@{changed=($out -ne $Source);source=$out;action='BALANCED_MISSING_DELIMITER'}}
function Write-RunReport($obj){$p=Join-Path $ReportDir (([IO.Path]::GetFileName($Artifact))+'.'+(Get-Date -Format 'yyyyMMdd-HHmmssfff')+'.json');$obj|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $p -Encoding UTF8;Write-Event ('REPORT '+$p)}
$history=New-Object 'System.Collections.Generic.List[object]';$perError=@{};$attempt=0;$source=Get-Content -LiteralPath $Candidate -Raw -Encoding UTF8;$previousHash='';$verdict='UNKNOWN_ERROR'
while($true){$attempt++;if($attempt -gt $EmergencyCeiling){$verdict='EMERGENCY_CEILING';break};if($attempt -gt $MaxAttempts){$verdict='REPAIR_ATTEMPT_CEILING';break};$candidateHash=Hash-Text $source;Write-Event ("SYNTAX attempt $attempt candidate=$candidateHash");$r=Get-ParserResult $source;if($r.pass){Write-Event 'SYNTAX PASS';$verdict=if($attempt -eq 1){'SYNTAX_PASS'}else{'SYNTAX_REPAIR_SUCCESS'};break};$cooked=$false;foreach($e in @($r.errors)){$fp=if(Get-Command Get-ErrorFingerprint -ErrorAction SilentlyContinue){Get-ErrorFingerprint $e.message 'PARSER'}else{Hash-Text ('PARSER|'+$e.message)};if(-not $perError.ContainsKey($fp)){$perError[$fp]=0};$perError[$fp]++;$history.Add([ordered]@{attempt=$attempt;fingerprint=$fp;message=$e.message;line=$e.line;column=$e.column});if(Get-Command Save-ErrorEvent -ErrorAction SilentlyContinue){[void](Save-ErrorEvent -Source 'UAUD' -Stream 'Parser' -Text $e.message -Artifact $Artifact -CandidateHash $candidateHash -PreviousCandidateHash $previousHash -Attempt $attempt -SyntaxResult 'FAIL' -Context ("line=$($e.line) column=$($e.column)"))};if($perError[$fp] -ge $RepeatedErrorThreshold){$cooked=$true}};if($cooked){Write-Event 'COOKED_REPEATED_ERROR';$verdict='COOKED_REPEATED_ERROR';break};$repair=Invoke-DeterministicRepair $source $r;if(-not $repair.changed){$verdict='UNKNOWN_ERROR';break};$newResult=Get-ParserResult $repair.source;if(@($newResult.errors).Count -ge @($r.errors).Count){$verdict='NON_PROGRESSING_REPAIR';break};Write-Event ('REPAIR '+$repair.action);$previousHash=$candidateHash;$source=$repair.source}
if($verdict -in @('SYNTAX_PASS','SYNTAX_REPAIR_SUCCESS') -and $Canonical){try{$null=Get-Content -LiteralPath $Canonical -Raw -Encoding UTF8|ConvertFrom-Json -ErrorAction Stop}catch{$verdict='CANONICAL_INVALID'};if($verdict -in @('SYNTAX_PASS','SYNTAX_REPAIR_SUCCESS')){Write-Event 'AST PASS; artifact-specific canonical comparator required.';$verdict='AST_PASS_CANONICAL_COMPARATOR_REQUIRED'}}
$report=[ordered]@{schema=1;uaud_version='1.0.1';artifact=$Artifact;candidate_hash=Hash-Text $source;attempts=$attempt;error_history=@($history);per_error=$perError;final_verdict=$verdict;behavioural_stage='EXTERNAL_ISOLATED_WINDOWS_CI';install_allowed=$false};Write-RunReport $report;$report|ConvertTo-Json -Depth 20;if($verdict -in @('SYNTAX_PASS','SYNTAX_REPAIR_SUCCESS')){exit 0}else{exit 1}
